version: '3.8'

services:
 backend:
   build: ./backend
   volumes:
     - ./backend:/app
   ports:
     - "8000:8000"
   environment:
     - OPENAI_API_KEY=<PASTE_YOUR_KEY>
   command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --ws-max-size 10000000 --ws-ping-interval 20

 frontend:
   build: ./frontend
   volumes:
     - ./frontend:/app
     - /app/node_modules
   ports:
     - "3000:3000"
   depends_on:
     - backend

 db:
   image: postgres:13
   volumes:
     - postgres_data:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: assistants_db

 adminer:
    image: bangdig.gitlab.yandexcloud.net:5050/bang-digital/devops/images/adminer:4.8.1-standalone
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
    ports:
      - "8080:8080"

volumes:
 postgres_data: